###
GET http://localhost:37137/fit/vle
Accept: application/json

###

POST http://localhost:37137/fit/vle
Content-Type: application/json

{"compound1": "EtOH", "compound2": "H2O", "model_name": "vanLaar", "datasets":  ["Voutsas2011"],
  "skip_optimization": false, "nparams0": {"A_12": 0.4, "A_21": 0.1}}

###

POST http://localhost:37137/fit/vle
Content-Type: application/json

{"compound1": "CHOL", "compound2": "CHF", "model_name": "NRTL", "datasets":  ["10kPa", "25kPa", "40kPa"],
  "const_param_names": ["c_12"]}

###
# @no-log
DELETE http://localhost:37137/fit/vle
Content-Type: application/json

{"compound1": "EtOH", "compound2": "H2O", "model_name": "vanLaar"}

###
# @no-log
POST http://localhost:37137/fit/vapor
Content-Type: application/json

{
  "compound": "CHF2",
  "model_name": "Wagner",
  "p_data": [9.98, 11.52, 14.39, 25.01, 25.95, 39.91, 40.05, 52.5, 60.41, 78.21, 89.63, 100.05],
  "T_data": [363.95, 367.65, 373.55, 389.25, 390.25, 403.35, 403.55, 412.45, 417.15, 426.25, 431.25, 435.35],
  "nparams0": {"A": -7.898313, "B": 1.997515, "C": -2.448405, "D": -1.880206, "T_c": 647, "p_c": 22071}
}

###

POST http://localhost:37137/fit/vle/tabulate
Content-Type: application/json

{"compound1": "CHOL", "compound2": "CHF", "model_name": "NRTL", "p_spec":  33}

###

POST http://localhost:37137/fit/vle/tabulate
Content-Type: application/json

{"compound1": "CHOL", "compound2": "CHF", "model_name": "NRTL", "T_spec":  365}

###
