
POST http://localhost:37137/td_test/gamma
Content-Type: application/json

{"compound1": "CHOL", "compound2": "CHF", "dataset": "10kPa"}

###

POST http://localhost:37137/td_test/slope
Content-Type: application/json

{"compound1": "CHOL", "compound2": "CHF", "dataset": "10kPa"}

###

POST http://localhost:37137/td_test/rk
Content-Type: application/json

{"compound1": "CHOL", "compound2": "CHF", "dataset": "10kPa"}

###

POST http://localhost:37137/td_test/herington
Content-Type: application/json

{"compound1": "CHOL", "compound2": "CHF", "dataset": "10kPa"}

###

POST http://localhost:37137/td_test/fredenslund
Content-Type: application/json

{"compound1": "CHOL", "compound2": "CHF", "dataset": "10kPa", "legendre_order": 4}

###

POST http://localhost:37137/td_test/van_ness
Content-Type: application/json

{"compound1": "CHOL", "compound2": "CHF", "dataset": "10kPa", "model_name": "NRTL"}

###
