###
GET http://127.0.0.1:37137/vapor
Accept: application/json

###
GET http://127.0.0.1:37137/vapor/definitions
Accept: application/json

###

POST http://localhost:37137/vapor/analysis
Content-Type: application/json

{"compound": "CHOL"}

###
# @no-log
PUT http://localhost:37137/vapor
Content-Type: application/json

{"model_name": "Antoine", "compound": "WHAT", "T_min": 262, "T_max": 363, "params": [7714, 0.2, 1.234e-7]}

###
# @no-log
DELETE http://localhost:37137/vapor
Content-Type: application/json

{"model_name": "Antoine", "compound": "WHAT"}

###
