###
GET http://127.0.0.1:37137/vapor
Accept: application/json

###
GET http://127.0.0.1:37137/vapor/definitions
Accept: application/json

###

POST http://localhost:37137/vapor/analysis
Content-Type: application/json

{"compound": "CHOL"}

###
# @no-log
PUT http://localhost:37137/vapor
Content-Type: application/json

{"model_name": "Wagner", "compound": "WHAT", "T_min": 262, "T_max": 363, "nparams": {"A": -7.898313, "B": 1.997515, "C": -2.448405, "D": -1.880206, "T_c": 647.1081, "p_c": 22071.54985}}
###
# @no-log
DELETE http://localhost:37137/vapor
Content-Type: application/json

{"model_name": "Wagner", "compound": "WHAT"}

###
